// Module included in the following assemblies:
//
// * observability/monitoring/enabling-monitoring-for-user-defined-projects.adoc

:_mod-docs-content-type: PROCEDURE
[id="creating-cluster-with-aws-kms-key_{context}"]
= Creating a {product-title} cluster using a custom AWS KMS key

[role="_abstract"]
You can create a {product-title} cluster with a customer-provided KMS key that is used to encrypt either node root volumes, the etcd database, or both. A different KMS key ARN can be provided for each option.

[NOTE]
====
{product-title} does not automatically configure the `default` storage class to encrypt persistent volumes with the customer-provided KMS key. This is something that can be configured in-cluster after installation.
====


.Procedure

. Create a custom AWS customer-managed KMS key by running the following command:
+
[source,terminal]
----
$ KMS_ARN=$(aws kms create-key --region $AWS_REGION --description 'Custom ROSA Encryption Key' --tags TagKey=red-hat,TagValue=true --query KeyMetadata.Arn --output text)
----
+
This command saves the Amazon Resource Name (ARN) output of this custom key for further steps.
+
[NOTE]
====
Customers must provide the `--tags TagKey=red-hat,TagValue=true` argument that is required for a customer KMS key.
====


. Verify the KMS key has been created by running the following command:
+
[source,terminal]
----
$ echo $KMS_ARN
----

. Set your AWS account ID to an environment variable.
+
[source,terminal]
----
$ AWS_ACCOUNT_ID=<aws_account_id>
----

. Set your Account Role Prefix to an environment variable.
+
[source,terminal]
----
$ ACCOUNT_ROLE_PREFIX=<account_role_prefix>
----

. Set your Operator Role Prefix to an environment variable.
+
[source,terminal]
----
$ OPERATOR_ROLE_PREFIX=<operator_role_prefix>
----
. Add the ARN for the account-wide installer role and operator roles that you created in the preceding step to the `Statement.Principal.AWS` section in the file. In the following example, the ARN for the default `ManagedOpenShift-HCP-ROSA-Installer-Role` role is added:
+
[source,terminal]
----
{
  "Version": "2012-10-17",
  "Id": "key-rosa-policy-1",
  "Statement": [
    {
      "Sid": "Enable IAM User Permissions",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::${AWS_ACCOUNT_ID}:root"
      },
      "Action": "kms:*",
      "Resource": "*"
    },
    {
      "Sid": "Installer Permissions",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::${AWS_ACCOUNT_ID}:role/${ACCOUNT_ROLE_PREFIX}-HCP-ROSA-Installer-Role"
      },
      "Action": [
        "kms:CreateGrant",
        "kms:DescribeKey",
        "kms:GenerateDataKeyWithoutPlaintext"
      ],
      "Resource": "*"
    },
    {
      "Sid": "Support Permissions",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::${AWS_ACCOUNT_ID}:role/${ACCOUNT_ROLE_PREFIX}-HCP-ROSA-Support-Role"
      },
      "Action": "kms:DescribeKey",
      "Resource": "*"
    },
    {
      "Sid": "ROSA KubeControllerManager Permissions",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::${AWS_ACCOUNT_ID}:role/${OPERATOR_ROLES_PREFIX}-kube-system-kube-controller-manager"
      },
      "Action": "kms:DescribeKey",
      "Resource": "*"
    },
    {
      "Sid": "ROSA KMS Provider Permissions",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::${AWS_ACCOUNT_ID}:role/${OPERATOR_ROLES_PREFIX}-kube-system-kms-provider"
      },
      "Action": [
        "kms:Encrypt",
        "kms:Decrypt",
        "kms:DescribeKey"
      ],
      "Resource": "*"
    },
    {
      "Sid": "ROSA NodeManager Permissions",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::${AWS_ACCOUNT_ID}:role/${OPERATOR_ROLES_PREFIX}-kube-system-capa-controller-manager"
      },
      "Action": [
        "kms:DescribeKey",
        "kms:GenerateDataKeyWithoutPlaintext",
        "kms:CreateGrant"
      ],
      "Resource": "*"
    },
    {
      "Sid": "ROSA EBS CSI Driver Permissions",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::${AWS_ACCOUNT_ID}:role/${OPERATOR_ROLES_PREFIX}-openshift-cluster-csi-drivers-ebs-cloud-credentials"
      },
      "Action": [
        "kms:Encrypt",
        "kms:Decrypt",
        "kms:ReEncrypt*",
        "kms:GenerateDataKey*",
        "kms:DescribeKey"
      ],
      "Resource": "*"
    },
    {
      "Sid": "ROSA EBS CSI Driver Grant Permissions",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::${AWS_ACCOUNT_ID}:role/${OPERATOR_ROLES_PREFIX}-openshift-cluster-csi-drivers-ebs-cloud-credentials"
      },
      "Action": [
        "kms:CreateGrant",
        "kms:RevokeGrant",
        "kms:ListGrants"
      ],
      "Resource": "*",
      "Condition": {
        "Bool": {
          "kms:GrantIsForAWSResource": "true"
        }
      }
    }
  ]
}
----
+
[NOTE]
====
To encrypt persistent volumes with a custom KMS key, customers must include the EBS CSI driver's IAM role in the KMS key policy
====

. Confirm the details of the policy file created by running the following command:
+
[source,terminal]
----
$ cat rosa-key-policy.json
----

. Apply the newly generated key policy to the custom KMS key by running the following command:
+
[source,terminal]
----
$ aws kms put-key-policy --key-id $KMS_ARN \
--policy file://rosa-key-policy.json \
--policy-name default
----

. Create the cluster by running the following command:
+
--
include::snippets/rosa-long-cluster-name.adoc[]
--
+
[source,terminal]
----
$ rosa create cluster --cluster-name <cluster_name> \ 
--subnet-ids <private_subnet_id>,<public_subnet_id> \
--sts \
--mode auto \
--machine-cidr 10.0.0.0/16 \
--compute-machine-type m5.xlarge \
--hosted-cp \
--region <aws_region> \
--oidc-config-id $OIDC_ID \
--kms-key-arn $KMS_ARN \
--etcd-encryption-kms-arn $KMS_ARN \
--operator-roles-prefix $OPERATOR_ROLES_PREFIX
----
+
--
where:

`--kms-key-arn`:: This KMS key ARN is used to encrypt all worker node root volumes. It is not required if only etcd database encryption is needed.
`--etcd-encryption-kms-arn`:: This KMS key ARN is used to encrypt the etcd database. The etcd database is always encrypted by default with an AES cipher block, but can be encrypted instead with a KMS key. It is not required if only node root volume encryption is needed.
--

.Verification

You can verify that your KMS key works by using {cluster-manager-url}. 

. Navigate to {cluster-manager-url} and select *Instances*.

. Select your instance.

. Click the *Storage* tab.

. Copy the *KMS key ID*.

. Search and select *Key Management Service*.

. Enter your copied _KMS key ID_ in the *Filter* field.
